apiVersion: v1
kind: Service
metadata:
  name: ubuntu-desktop-lxde-vnc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ubuntu-desktop-lxde-vnc"
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    app: ubuntu-desktop-lxde-vnc
